// AUTO-GENERATED by scripts/proto-meta.js — do not edit by hand.
export interface ProtoMetaInfo {
  /** ISO date of the last commit touching the prototype */
  updated?: string;
  /** Last human author of the prototype */
  author?: string;
  /** true when src/assets/previews/{slug}.jpg exists */
  preview?: boolean;
}

export const PROTO_META: Record<string, ProtoMetaInfo> = {
  "deal-room": {
    "updated": "2026-06-03T09:55:33+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "project-archive-creation-flow-testing": {
    "updated": "2026-06-03T13:20:50+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "ca-settings-integrations": {
    "updated": "2026-09-28T12:12:04+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "my-prototype-delete-account": {
    "updated": "2026-05-26T13:05:42+03:00",
    "author": "Dmitriy Siniehin"
  },
  "insights-activity-log": {
    "updated": "2026-06-03T09:55:33+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "ca-create-api-key": {
    "updated": "2026-05-26T10:53:19+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "quick-access-panel": {
    "updated": "2026-09-02T15:37:22+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "permission-search": {
    "updated": "2026-05-26T10:53:19+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "terms-of-use-create": {
    "updated": "2026-05-26T10:53:19+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "view-as-mode": {
    "updated": "2026-06-03T09:55:33+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "timezone-picker": {
    "updated": "2026-06-03T09:55:33+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "q-a-drag-and-drop": {
    "updated": "2026-06-04T12:19:17+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "search-results-pagination": {
    "updated": "2026-06-03T09:55:33+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "ifs-ai": {
    "updated": "2026-06-04T12:19:17+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "redaction-viewer": {
    "updated": "2026-06-09T17:20:27+02:00",
    "author": "Nikita Tonkonozhenko",
    "preview": true
  },
  "branding-page": {
    "updated": "2026-08-11T14:06:39+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "global-ai": {
    "updated": "2026-06-24T12:20:33+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "qna-answer-editor": {
    "updated": "2026-08-12T11:55:47+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "ai-assistant": {
    "updated": "2026-09-02T16:17:57+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "permissions-legend": {
    "updated": "2026-09-15T15:43:29+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "permissions-legend-v2": {
    "updated": "2026-09-16T21:17:27+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "permissions-legend-v3": {
    "updated": "2026-10-02T16:08:26+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "added-column-hover": {
    "updated": "2026-09-02T15:37:22+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "permission-icon-animation": {
    "updated": "2026-09-22T12:25:49+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "editor-color-contrast": {
    "updated": "2026-09-22T14:04:01+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "column-admin-hint": {
    "updated": "2026-09-24T15:12:31+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "docs-ai-search": {
    "updated": "2026-10-05T17:51:29+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "dashboard-ai-search": {
    "updated": "2026-09-28T13:02:30+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "reports-ai-search": {
    "updated": "2026-09-28T13:02:30+03:00",
    "author": "Dmitriy Siniehin",
    "preview": true
  },
  "mobile-doc-filters": {
    "updated": "2026-09-28T12:19:46+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "qna-column-resize": {
    "updated": "2026-09-30T13:27:48+03:00",
    "author": "Yuliia Porokhivnyk",
    "preview": true
  },
  "qna-setup-canvas": {
    "updated": "2026-10-08T21:06:28+03:00",
    "author": "Dmitriy Siniehin"
  },
  "checklist-matching": {
    "updated": "2026-10-09T16:06:09+03:00",
    "author": "Dmitriy Siniehin"
  },
  "checklist-matching-inline": {
    "updated": "2026-10-09T16:06:09+03:00",
    "author": "Dmitriy Siniehin"
  }
};
