#!/usr/bin/env node
/**
 * Generates src/app/proto-meta.generated.ts — per-prototype freshness info for the dashboard:
 *   slug → { updated (ISO date of last commit touching the prototype folder), author, preview }
 *
 * Source of truth is git history (author names normalised via .mailmap; agent commits
 * by "Claude" are skipped for the author but still count for the date).
 * `preview` is true when src/assets/previews/{slug}.jpg exists (see scripts/proto-previews.js).
 *
 * Runs in `npm run build:proto`. Shallow clones (Vercel git deploys) are unshallowed first.
 * Without git at all (`vercel --prod` CLI uploads) it keeps the committed file, so commit
 * the regenerated file too:   node scripts/proto-meta.js
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src/app/proto-meta.generated.ts');
const ROUTES = path.join(ROOT, 'src/app/app.routes.ts');
const REGISTRY = path.join(ROOT, 'src/app/proto-registry.ts');
const PREVIEWS = path.join(ROOT, 'src/assets/previews');
const BOT_AUTHORS = new Set(['Claude']);

const git = (cmd) => execSync(`git ${cmd}`, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();

let usable = false;
try {
  if (git('rev-parse --is-shallow-repository') === 'true') {
    // Vercel git deploys clone shallowly — fetch full history so dates are current
    execSync('git fetch --unshallow --quiet', { cwd: ROOT, stdio: 'ignore', timeout: 60000 });
  }
  usable = git('rev-parse --is-shallow-repository') === 'false';
} catch {}
if (!usable) {
  console.log('proto-meta: no full git history — keeping committed proto-meta.generated.ts');
  process.exit(0);
}

const slugs = [...fs.readFileSync(REGISTRY, 'utf8').matchAll(/slug:\s*'([^']+)'/g)].map(m => m[1]);
const routes = fs.readFileSync(ROUTES, 'utf8');

/** Folder of the component the route lazy-loads, e.g. src/app/prototypes/docs-ai-search */
function dirFor(slug) {
  const re = new RegExp(`path:\\s*'${slug.replace(/[-]/g, '\\-')}'[\\s\\S]{0,300}?import\\('\\./([^']+)'\\)`);
  const m = routes.match(re);
  if (m) return path.posix.dirname(`src/app/${m[1]}`);
  const fallback = `src/app/prototypes/${slug}`;
  return fs.existsSync(path.join(ROOT, fallback)) ? fallback : null;
}

const meta = {};
for (const slug of slugs) {
  const entry = {};
  const dir = dirFor(slug);
  if (dir) {
    const log = git(`log --format=%aI%x09%aN -- "${dir}"`).split('\n').filter(Boolean);
    if (log.length) {
      entry.updated = log[0].split('\t')[0];
      const human = log.map(l => l.split('\t')[1]).find(a => !BOT_AUTHORS.has(a));
      if (human) entry.author = human;
    }
  }
  if (fs.existsSync(path.join(PREVIEWS, `${slug}.jpg`))) entry.preview = true;
  meta[slug] = entry;
}

const body = `// AUTO-GENERATED by scripts/proto-meta.js — do not edit by hand.
export interface ProtoMetaInfo {
  /** ISO date of the last commit touching the prototype */
  updated?: string;
  /** Last human author of the prototype */
  author?: string;
  /** true when src/assets/previews/{slug}.jpg exists */
  preview?: boolean;
}

export const PROTO_META: Record<string, ProtoMetaInfo> = ${JSON.stringify(meta, null, 2)};
`;
fs.writeFileSync(OUT, body);
console.log(`proto-meta: wrote ${Object.keys(meta).length} entries → ${path.relative(ROOT, OUT)}`);
